-- Insere Disciplinas

-- Disciplinas ADS
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('AAG001','Administração Geral',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('IAC001','Arquitetura e Organização de Computadores',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('IAL002','Algoritmos e Lógica de Programação',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('IHW100','Laboratório de Hardware',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('ILM001','Programação em Microinformática',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('LIN100','Inglês I',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('MMD001','Matemática Discreta',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('CCG001','Contabilidade',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('IES100','Engenharia de Software',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('ILP010','Linguagem de Programação',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('ISI002','Sistemas de Informação',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('LIN200','Inglês II',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('LPO001','Comunicação e Expressão',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('MCA002','Cálculo',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('CEF100','Economia e Finanças',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('HST002','Sociedade e Tecnologia',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('IED001','Estrutura de Dados',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('IES200','Engenharia de Software II',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('IHC001','Interação Humano Computador',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('ISO100','Sistemas Operacionais I',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('LIN300','Inglês III',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('MET100','Estatística Aplicada',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('IBD002','Banco de Dados',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('IES300','Engenharia de Software III',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('ILP007','Programação Orientada a Objetos',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('ILP506','Eletiva – Programação para Dispositivos Móveis',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('ISO200','Sistemas Operacionais II',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('LIN400','Inglês IV',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TTG001','Metodologia da Pesquisa Científico-Tecnológica',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('IBD100','Laboratório de Banco de Dados (Escolha 1)',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('IES301','Laboratório de Engenharia de Software',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('IRC008','Redes de Computadores',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('IRC500','Eletiva – Projeto de Redes de Computadores',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('ISG003','Segurança da Informação',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('LIN500','Inglês V',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('MPL001','Programação Linear e Aplicações',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TTG003','Trabalho de Graduação I',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('AGO005','Gestão de Projetos',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('AGR101','Gestão de Equipes',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('CEE002','Empreendedorismo',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('HSO003','Ética e Responsabilidade Profissional',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('IIA002','Inteligência Artificial (Escolha 3)',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('ITE002','Tópicos Especiais em Informática (Escolha 2)',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('ITI004','Gestão e Governança de Tecnologia da Informação',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('LIN600','Inglês VI',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TES001','Estágio Supervisionado',1);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TTG103','Trabalho de Graduação II',1);

-- Disciplinas Logística

INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TJI001','Projeto Interdisciplinar I',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('JLG951','Logística',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('AAG001','LOG – Administração Geral',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('INF001','Informática Básica',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('MCA003','Cálculo I',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TTG100','Métodos para a Produção do Conhecimento',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('LPO001','LOG – Comunicação e Expressão',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('LIN100','LOG – Inglês I',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TJI002','Projeto Interdisciplinar II',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('RTI002','Modalidade e Intermodalidade',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('CCG001','LOG – Contabilidade',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('AGQ001','Fundamentos de Gestão da Qualidade',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('MET102','Estatística Aplicada à Gestão',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('MCA022','Cálculo Diferencial e Integral',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('MMF001','Matemática Financeira',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('LES100','Espanhol I',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('LIN200','LOG – Inglês II',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TJI003','Projeto Interdisciplinar III',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('JGT001','Gestão Tributária nas Operações Logísticas',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('CEF003','Economia e Finanças Empresariais',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('AGP300','Gestão de Produção e Operações',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('AGR101','LOG – Gestão de Equipes',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('MPO100','Pesquisa Operacional',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('LES200','Espanhol II',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('LIN300','LOG – Inglês III',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TJI004','Projeto Interdisciplinar IV',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('JTL001','Custos e tarifas Logísticos',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('JMT001','Sistemas de Movimentação e Transporte',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('ETG006','Gestão de Tráfico Urbano',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('AGS004','Gestão de Estoques',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('PMG001','Fundamentos de Marketing',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('EPQ100','Métodos Quantitativos Aplicados',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('LIN400','LOG – Inglês IV',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TJI005','Projeto Interdisciplinar V',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('JMA001','Movimentação e Armazenagem',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('JEU001','Embalagens e Unitização',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('AGS003','Gestão da Cadeia de Suprimentos',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TPJ200','Projeto Aplicado à Logística',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('JSL001','Simulação em Logística',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('CEE001','Inovação e Empreendedorismo',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('LIN500','LOG – Inglês V',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TJI006','Projeto Interdisciplinar VI',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('ACE100','Comércio Exterior e Logística',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('ETP002','Mobilidade Urbana',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('JTR001','Gestão de Transporte de Carga e Roteirização',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('ETG002','Tecnologia de Transportes',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('ETE001','Transportes de Cargas Especiais',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('ITI100','Tecnologia da Informação aplicada à Logística',2);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('LIN600','LOG – Inglês VI',2);

-- Disciplinas Gestão Empresarial

INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE001','GE - Administração Geral',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE002','GE – Comunicação e Expressão',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE003','GE – Contabilidade',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE004','Informática Aplicada à Gestão',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE005','GE – Inglês I',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE006','Matemática para Gestão',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE007','Sociedade, Tecnologia e Inovação',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE008','Atividades Acadêmico-Científico-Culturais I',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE009','Comportamento Organizacional',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE010','Estatística aplicada à Gestão',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE011','Gestão Ambiental',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE012','Economia',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE013','GE – Inglês II',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE014','Métodos para a Produção do Conhecimento',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE015','Sociologia das Organizações',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE016','Gestão de Marketing',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE017','Gestão de Pessoas',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE018','GE – Inglês III',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE019','GE – Matemática Financeira',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE020','Organização, Sistemas e Métodos',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE021','GE – Sistemas de Informação',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE022','Comunicação Empresarial Geral',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE023','Direito Empresarial',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE024','Gestão Fincanceira',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE025','GE – Inglês IV',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE026','GE – Logística',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE027','Planejamento de Marketing',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE028','Análise de Investimentos',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE029','GE – Espanhol I',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE030','Gestão da Produção',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE031','GE – Fundamentos da Gestão da Qualidade',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE032','Gestão de Projetos Empresariais',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE033','GE – Inglês V',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE034','Projeto de Trabalho de Graduação',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE035','Desenvolvimento de Negócios',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE036','GE – Espanhol II',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE037','GE – Inglês VI',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE038','Negócios Internacionais',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE039','Planejamento e Gestão Estratégica',3);
INSERT INTO seazs.tb_disciplina (codigo_siga,nome_disciplina,id_curso) VALUES ('TGE040','Sistemas Integrados de Gestão',3);
